server:
 port: 8093
eureka:
 client:
  fetch-registry: true
  register-with-eureka: true
  service-url:
   defaultZone: http://localhost:8761/eureka/
 instance:
  hostname: localhost
spring:
 application:
  name: API-GATEWAY
 cloud:
  gateway.mvc:
   routesMap:
    configRoute1:
     id: MICRO-USUARIOS-AREA
     uri: lb://MICRO-USUARIOS
     predicates:
      - path=/area/**
    configRoute2:
     id: MICRO-USUARIOS-ROL-USUARIOS
     uri: lb://MICRO-USUARIOS
     predicates:
      - path=/rol_usuarios/**
    configRoute3:
     id: MICRO-USUARIOS-USUARIOS-SESIONES
     uri: lb://MICRO-USUARIOS
     predicates:
      - path=/usuarios_sesiones/**
    configRoute4:
     id: MICRO-USUARIOS-USUARIOS
     uri: lb://MICRO-USUARIOS
     predicates:
      - path=/usuarios/**
    configRoute5:
     id: MICRO-EMPLEADOS-EMPLEADO
     uri: lb://MICRO-EMPLEADOS
     predicates:
      - path=/empleado/**
    configRoute6:
     id: MICRO-EMPLEADOS-EQUIPO
     uri: lb://MICRO-EMPLEADOS
     predicates:
      - path=/equipo/**
    configRoute7:
     id: MICRO-EMPLEADOS-ROL-EQUIPO
     uri: lb://MICRO-EMPLEADOS
     predicates:
      - path=/rol_equipo/**
    configRoute8:
     id: MICRO-APROBACION
     uri: lb://MICRO-APROBACION
     predicates:
      - path=/aprobacion/**
    configRoute9:
     id: MICRO-JEFE-AREA
     uri: lb://MICRO-JEFE-AREA
     predicates:
      - path=/jefe_area/**
    configRoute10:
     id: MICRO-JEFE-PROYECTO
     uri: lb://MICRO-JEFE-PROYECTO
     predicates:
      - path=/jefe_proyecto/**
    configRoute11:
     id: MICRO-PROYECTO-DOCUMENTO
     uri: lb://MICRO-PROYECTO
     predicates:
      - path=/documento/**
    configRoute12:
     id: MICRO-PROYECTO-PROYECTO
     uri: lb://MICRO-PROYECTO
     predicates:
      - path=/proyecto/**
    configRoute13:
     id: MICRO-SOLICITUD-CAMBIO
     uri: lb://MICRO-SOLICITUD-CAMBIO
     predicates:
      - path=/solicitud_cambio/**