server:
 port: 9087
spring:
 jpa:
  database: MYSQL
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/gestion_proyecto_solicitud_cambio?serverTimezone=UTC
  username: root
  password: Lucero00.
 messages:
  basename: messages
 application:
  name: MICRO-SOLICITUD-CAMBIO
eureka:
 instance:
  hostname: localhost
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka